### ISSUE TITLE
My antivirus says that it contains malware after installing

### ISSUE THREAD

**Issue by rudrasoftwarecorporation** [praveshagrawal/HTML-to-APK#2]

**Comment by PPPDUD** [comment]
Don't trust it. This is probably a false positive. If your antivirus is deleting or hiding away the file, fight back. Disable your antivirus temporarily and/or use WINE on a Linux desktop. Note that I have not tested any of these solutions yet. Also, please remember to give us your OS version and to tell us what antivirus you are using.

**Comment by praveshagrawal** [comment]
Issue resolved. Kindly use the latest version.
